// SPDX-License-Identifier: MIT

/**
 * Centralized API error codes for consistent responses.
 * These are the `code` values in `{ success: false, error: { code, message } }`.
 */

export const ERROR_CODES = {
  // 400 — Client errors
  BAD_REQUEST: "BAD_REQUEST",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_AMOUNT: "INVALID_AMOUNT",
  INVALID_ADDRESS: "INVALID_ADDRESS",
  INVALID_MEMO: "INVALID_MEMO",
  INVALID_ASSET: "INVALID_ASSET",

  // 401 — Authentication
  UNAUTHORIZED: "UNAUTHORIZED",
  INVALID_API_KEY: "INVALID_API_KEY",
  EXPIRED_API_KEY: "EXPIRED_API_KEY",

  // 403 — Authorization
  FORBIDDEN: "FORBIDDEN",
  NOT_OWNER: "NOT_OWNER",
  NOT_SIGNER: "NOT_SIGNER",

  // 404 — Not found
  NOT_FOUND: "NOT_FOUND",
  PAYMENT_NOT_FOUND: "PAYMENT_NOT_FOUND",
  ESCROW_NOT_FOUND: "ESCROW_NOT_FOUND",
  STREAM_NOT_FOUND: "STREAM_NOT_FOUND",
  BATCH_NOT_FOUND: "BATCH_NOT_FOUND",
  WEBHOOK_NOT_FOUND: "WEBHOOK_NOT_FOUND",

  // 409 — Conflict
  CONFLICT: "CONFLICT",
  UNIQUE_CONSTRAINT: "UNIQUE_CONSTRAINT",
  DUPLICATE_REQUEST: "DUPLICATE_REQUEST",

  // 429 — Rate limiting
  RATE_LIMITED: "RATE_LIMITED",

  // 500 — Server errors
  INTERNAL_ERROR: "INTERNAL_ERROR",
  DATABASE_ERROR: "DATABASE_ERROR",
  CONTRACT_ERROR: "CONTRACT_ERROR",
  CONTRACT_UNAVAILABLE: "CONTRACT_UNAVAILABLE",

  // Payment-specific
  INSUFFICIENT_FUNDS: "INSUFFICIENT_FUNDS",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  PAYMENT_CANCELLED: "PAYMENT_CANCELLED",
  TRANSACTION_FAILED: "TRANSACTION_FAILED",

  // Multisig-specific
  THRESHOLD_NOT_MET: "THRESHOLD_NOT_MET",
  ALREADY_APPROVED: "ALREADY_APPROVED",
  ALREADY_EXECUTED: "ALREADY_EXECUTED",

  // Governance
  PROPOSAL_NOT_FOUND: "PROPOSAL_NOT_FOUND",
  VOTING_ENDED: "VOTING_ENDED",
  PROPOSAL_ALREADY_EXECUTED: "PROPOSAL_ALREADY_EXECUTED",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

/** HTTP status codes for each error code */
export const ERROR_STATUS: Record<string, number> = {
  BAD_REQUEST: 400,
  VALIDATION_ERROR: 400,
  INVALID_AMOUNT: 400,
  INVALID_ADDRESS: 400,
  INVALID_MEMO: 400,
  INVALID_ASSET: 400,
  UNAUTHORIZED: 401,
  INVALID_API_KEY: 401,
  EXPIRED_API_KEY: 401,
  FORBIDDEN: 403,
  NOT_OWNER: 403,
  NOT_SIGNER: 403,
  NOT_FOUND: 404,
  PAYMENT_NOT_FOUND: 404,
  ESCROW_NOT_FOUND: 404,
  STREAM_NOT_FOUND: 404,
  BATCH_NOT_FOUND: 404,
  WEBHOOK_NOT_FOUND: 404,
  CONFLICT: 409,
  UNIQUE_CONSTRAINT: 409,
  DUPLICATE_REQUEST: 409,
  RATE_LIMITED: 429,
  INTERNAL_ERROR: 500,
  DATABASE_ERROR: 500,
  CONTRACT_ERROR: 500,
  CONTRACT_UNAVAILABLE: 503,
  INSUFFICIENT_FUNDS: 402,
  PAYMENT_FAILED: 500,
  PAYMENT_CANCELLED: 400,
  TRANSACTION_FAILED: 500,
  THRESHOLD_NOT_MET: 400,
  ALREADY_APPROVED: 409,
  ALREADY_EXECUTED: 409,
  PROPOSAL_NOT_FOUND: 404,
  VOTING_ENDED: 400,
  PROPOSAL_ALREADY_EXECUTED: 409,
};
