import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      "contracts/**",
      "public/**",
      "prisma/**",
      "scripts/**",
      "*.config.{mjs,ts}",
      "next-env.d.ts", // auto-generated by Next.js, not committed
      "playwright-report/**",
      "test-results/**",
    ],
  },
];

export default eslintConfig;
